server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_tercero?useSSL=false&useTimezone=true&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      #ddl-auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace